### ISSUE TITLE
Update links exercise on github.io

### ISSUE THREAD

**Issue by pyramid-songs** [holochain-gym/holochain-gym.github.io#23]
After the solution has been removed from the master branch, I should go through the links tutorial page and make some general updates to the information. In addition, I'll also implement the challenge questions, and then update the tests as needed.

**Comment by tixel** [comment]
@guillemcordoba @pyramid-songs 
I'm adding some extra text to the links chapter.

Oké if I add the existing exercise as well?

If you want to look at my proposed changes:
https://github.com/tixel/holochain-gym.github.io/blob/master/docs/developers/basic/links.md

My additions assume this chapter comes directly after the source chain chapter.

**Comment by guillemcordoba** [comment]
Mmm let's talk about this in the next call, I have a strong sense that we don't want to introduce headers or source-chains before links. Links are the most basic primitive of holochain just after entries, and multiple iterations of explaining things to people have shown that in my experience it's better to describe holochain as a primarily distributed graph-database (not thinking about headers at all), and then introduce the local source-chain concept.
