### ISSUE TITLE
add exercise to source chain chapter

### ISSUE THREAD

**Issue by tixel** [holochain-gym/holochain-gym.github.io#24]

**Comment by guillemcordoba** [comment]
Do you think we need a separate elements chapter? I think it would be good to show different elements and their contents, as a semi-step building up to the source-chain, where doing a `query` will surely be the main thing. I can do the elements one :)

**Comment by tixel** [comment]
Hi Guillem,
The query stuff is new to me.

I was doubting between  
first explaining the fundamentals: entries, hashes, headers, source chain 
in there most basic form, with little distraction
to ease people in to Rust & holochain
And then in the 2nd part of Basic exercises 
to start focusing on everything you need to build happs:
elements+queries, links, anchors

But it is probably easier to decide the right structure once we have all the building blocks.
We can even A/B test it if we want :-D

I commited my work in progress (chapter & exercises) on the source-chain in my forks. So you can peek there to get an idea of where I am going and to give feedback.
Especially on my Rust code, because my code still gives me very clunky and unnatural impression.

**Comment by guillemcordoba** [comment]
Hey @tixel , I do think it's important to introduce `query` as the main thing in the source chain exercise. Docs: https://docs.rs/hdk/0.0.100/hdk/chain/fn.query.html

Query is basically a mechanism by which you filter and get elements (headers + entries) from your source-chain, not the DHT. I think this is fundamental for people to get a first step towards the aha moment of "aaah, I can rely on mainly two sources of truth, with fundamentally different properties".

What do you think?

**Comment by guillemcordoba** [comment]
Oh wow I just saw that you manually implemented a query through gets with the `happened_before`. This is creative! So I think we are on the same page. I think also adding an interaction to the gym that allows you to select different agents and see that their chains evolve independently would be quite good, what do you think?
