### ISSUE TITLE
Give text a max width for better readability

### ISSUE THREAD

**Issue by tixel** [holochain-gym/holochain-gym.github.io#26]
Long and width text is harder to read.
With some CSS changes we could give text a max-width, while still using all available space for the simulation.
I'm not sure where or how to add this in the current setup.

Example:
![image](https://user-images.githubusercontent.com/380643/114293427-36cb5800-9a96-11eb-9fbe-bfd1d1eadc44.png)

CSS used to get screenshot

p {
  max-width: 50rem;
  text-align: justify;
} 

pre {
  max-width: 50rem;
  text-align: justify;
}

ul {
  max-width: 50rem;
  text-align: justify;
}

inline-notification {
    max-width: 50rem;
}

**Comment by guillemcordoba** [comment]
Awesome @tixel , we can override the CSS for the gym at `docs/_assets/variables.css` I think this is a good idea, yes!
