### ISSUE TITLE
[Intermediate: Anchors] Contains Wrong Exercise

### ISSUE THREAD

**Issue by 0phelia36** [holochain-gym/holochain-gym.github.io#33]
The Intermediate "Anchors" exercise contains the exact same content as the Basic "Attaching Links" exercise, also might be a duplicate since I imagine it should contain the content of the Intermediate "Paths" exercise.

**Comment by guillemcordoba** [comment]
Yes, thanks... There are multiple exercises that are yet to be done, like Update, Delete... I will be looking into doing them in the near future. Would you be excited to propose an exercise for anchors? With guidance from us of course :)

**Comment by 0phelia36** [comment]
So I've just spent some time learning holochain over the past few weeks and don't have a great deal of familiarity with it, I was under the impression that anchors didn't exist at all under with the newest version of holochain and had been entirely replaced by paths but looking through the docs it looks like they do.

Is there any use case for anchors that is better than using paths? If so I might be able to come up with something for an exercise, but otherwise I don't really see the point.

**Comment by guillemcordoba** [comment]
That's awesome :)

So Anchors do exist as a type in the new rsm version: https://docs.rs/hdk/0.0.100/hdk/hash_path/anchor/struct.Anchor.html, but they are only a simplified version of Paths. You can think of paths as anchor trees really, and paths will be the default and encouraged type to use.

However, the feedback we received from the paths exercise is that it was a bit too much to digest and understand at once. So we decided to split that exercise in two: first, the anchors exercise, in which you just train yourself to have a "global known entry" to which you attach links. Then, you go on to the paths exercise, in which you just expand that concept into "anchor trees", and understand the full implications of it.

Would this make more sense? How was your experience with the paths exercise? Would at least a playground simulation interaction make sense as the anchors exercise before moving on to paths?

Thanks a lot for reaching out :D

**Comment by 0phelia36** [comment]
Yeah that makes sense, the paths exercise definitely is a lot at once. For an anchor exercise how does using linking posts to an anchor for a get_all_posts query sound? So the expected output would just be implementing create_post and get_all_posts.

**Comment by guillemcordoba** [comment]
That's exactly what was on my mind :)

Do you wanna give the interaction a go? Doing something like [this](https://github.com/holochain-gym/holochain-gym.github.io/blob/main/docs/developers/intermediate/paths.md#try-it) that turns into [this](https://holochain-gym.github.io/developers/intermediate/paths/#try-it). If not, no worries, I can fill it in, do it only if you'd be excited.

**Comment by 0phelia36** [comment]
I made a PR for an anchors exercise here https://github.com/holochain-gym/holochain-gym.github.io/pull/36
