### ISSUE TITLE
Basic Entries Playground demo not working

### ISSUE THREAD

**Issue by stephenbpurkiss** [holochain-gym/holochain-gym.github.io#38]
Been looking at the code but can't see why the playground thingy isn't working on the entries page but is on others.

https://holochain-gym.github.io/developers/basic/entries/#try-it

Have tried different browsers ;)

Could be the content->greeting_text change, or new version of playground, or something else.

Been sifting through commits, notice quite a few merges from other trees so perhaps something wasn't in sync. Who knows? Not me, and it's melting my head so although I'm enjoying learning a bit more, I'm done for the night & thought I'd create an issue instead. Maybe next time I'll figure out the problem and post a patch!

Cheers

sbp

**Comment by guillemcordoba** [comment]
Awesome, thanks for spotting :)

**Comment by stephenbpurkiss** [comment]
I think you need to flush your caches, I've flushed mine and tried in Chrome and Safari but all I see is `[object Object]` no Playground

**Comment by stephenbpurkiss** [comment]
@guillemcordoba 
<img width="796" alt="Screenshot 2021-06-23 at 18 45 25" src="https://user-images.githubusercontent.com/6438292/123144395-8abdca00-d453-11eb-9835-98a9ce9a37e7.png">

**Comment by guillemcordoba** [comment]
Yeap saw that and fixed it, thanks!
