### ISSUE TITLE
[Holochain developer tools installation] Build fails on MacOS Big Sur

### ISSUE THREAD

**Issue by jost-s** [holochain-gym/holochain-gym.github.io#43]
When running `nix-shell` in the folder `developer-exercises`, the build fails with an error when compiling `holochain` itself.

That error is recorded here in the holonix repo https://github.com/holochain/holonix/issues/211. It's resolved in the current build, so `nix-shell https://nightly.holochain.love` as described in the [official docs](https://developer.holochain.org/install/#installing-the-holochain-dev-tools) works fine.

I suppose it's a matter of updating `default.nix` or mentioning in "Requirements -> Setup" that for MacOS 11 another version is needed.

**Comment by guillemcordoba** [comment]
Okey so that is interesting... In theory we *are* in the latest holonix version. Are you trying to enter the nix-shell with the latest version of the repo?

Any ideas @steveeJ?

**Comment by jost-s** [comment]
Yes, I have pulled most recent sources. The latest commit is from 29th of June.

**Comment by jost-s** [comment]
Sorry, I realize now that this is duplicate and in the wrong repo.

Duplicate of https://github.com/holochain-gym/developer-exercises/issues/39
