### ISSUE TITLE
Add exercise for hash

### ISSUE THREAD

**Issue by tixel** [holochain-gym/holochain-gym.github.io#9]
Explain what a hash it, why you need it in a holochain app.
get via entryhash
Have the exercise be a repetition of entries exercises maybe with minor extension (struct with fields?)
Let user add a test in typescript as extra learning item.

- [x] write text
- [x] add playground item to do a simulation
- [x] add exercise in zome
- [x] add exercise in typescript test
- [x] get feedback on text
- [x] get feedback on exercise

**Comment by guillemcordoba** [comment]
We can close this already right @tixel ?
